on:
  push:
    branches:    
      - 'gh-pages'
name: Pushing to FTP
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.cse1617a.site
        username: cse44@cse1617a.site
        password: ${{ secrets.FTP_PASSWORD}}
        server-dir: ./cv/
        local-dir: ./
        exclude: |
          **/.git*
